fix aero_model_readnl subroutine
NorESMhub/OsloSectional pull request #1
Opened 2024-10-07 07:48 UTC by Trudigard

Some updates on the namelist reading subroutine

2024-10-08 13:24 UTC, gold2718 requested changes
This looks pretty good!
I have some output suggestions.

2024-10-08 13:24 UTC, gold2718 commented on src/aero_model.F90
> +    call MPI_Bcast(aer_wetdep_list, len(aer_wetdep_list(1))*pcnst, mpi_character, mstrid, mpicom, ierr)
Please add an error check to each `MPI_Bcast` call:
```
if (ierr /= MPI_SUCCESS) then
   call endrun(subname//"Error "//int2str(ierr)//                       &
        " broadcasting 'aer_wetdep_list'")
end if
```
I know this was not previously in my namelist reading example, sorry for the inconvenience.

2024-10-11 09:11 UTC, gold2718 requested changes
This is looking good, just a minor addition and a suggestion.

2024-10-11 09:11 UTC, gold2718 commented on src/aero_model.F90
> +    if (ierr /= MPI_SUCCESS) then
I think you need to import `MPI_SUCCESS` above.
This would probably get caught during compilation . . . which means we need to figure out a way to build this.

2024-10-11 09:11 UTC, gold2718 commented on src/aero_model.F90
> +    do ind = 1, 1000
I know that `nwetdep` (and `ndrydep`) are initialized to zero in the module specification section but it is good practice to repeat that at the top of the loop to make it clear that all the counting is done here.
```suggestion
    nwetdep = 0
    do ind = 1, 1000
```

2024-10-11 11:28 UTC, gold2718 requested changes
Dang, found a new bit that needs fixing (how did this stuff ever work?).

2024-10-11 11:28 UTC, gold2718 commented on src/aero_model.F90
Agh, I just realized that these need to be the same size as in namelist_definition.xml
```suggestion
    character(len=16) :: aer_wetdep_list(1000) = ' '
    character(len=16) :: aer_drydep_list(1000) = ' '

```

2024-10-11 14:58 UTC, gold2718 approved these changes
Looks great now, thanks!

2024-10-11 15:02 UTC, Trudigard commented
Thanks for reviewing!
Who merges the PRs?

2024-10-11 15:09 UTC, merged